/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityComponent: typeof import('./src/components/b-activity/src/ActivityComponent.vue')['default']
    ActivityDetailsComponents: typeof import('./src/components/b-popup/src/ActivityDetailsComponents.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    ButtonComponent: typeof import('./src/components/b-utility/src/ButtonComponent.vue')['default']
    CreateActivityComponent: typeof import('./src/components/b-popup/src/CreateActivityComponent.vue')['default']
    DashboardComponent: typeof import('./src/components/b-dashboard/src/DashboardComponent.vue')['default']
    FiltersGroupComponent: typeof import('./src/components/b-filter/src/FiltersGroupComponent.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MenuButtonComponent: typeof import('./src/components/b-utility/src/MenuButtonComponent.vue')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    PopUpComponent: typeof import('./src/components/b-popup/src/PopUpComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShiftActivityComponent: typeof import('./src/components/b-activity/src/ShiftActivityComponent.vue')['default']
    SideContainerComponent: typeof import('./src/components/b-side-viewer/src/SideContainerComponent.vue')['default']
    SingleActivityComponent: typeof import('./src/components/b-activity/src/SingleActivityComponent.vue')['default']
    SingleFilterComponent: typeof import('./src/components/b-filter/src/SingleFilterComponent.vue')['default']
    StatisticComponent: typeof import('./src/components/b-utility/src/StatisticComponent.vue')['default']
    TitleComponent: typeof import('./src/components/b-title/src/TitleComponent.vue')['default']
    ToastComponent: typeof import('./src/components/b-popup/src/ToastComponent.vue')['default']
  }
}
